## code to prepare `sn_street_name_to_remove_df` dataset goes here
library("dplyr")

sn_street_name_to_remove_df <- dplyr::bind_rows(
  tibble::tibble(
    country = "Spain",
    string = c(
      "Calle de las ",
      "Calle de la ",
      "Calle de los ",
      "Calle del ",
      "Calle el ",
      "Calle de ",
      "Calle ",
      "Calleja ",
      "Callejón de ",
      "Callejón ",
      "Camino del ",
      "Camino de las ",
      "Camino de la ",
      "Camino de los ",
      "Camino de ",
      "Camino ",
      "Carretera de ",
      "Carretera ",
      "Cortafuego de las ",
      "Cortafuego ",
      "Plaza de la ",
      "Plaza de los ",
      "Plaza de ",
      "Plaza del ",
      "Plaza ",
      "Puente de ",
      "Puente del ",
      "Ronda del ",
      "Vereda de la ",
      "Vereda de los ",
      "Avenida de la ",
      "Avenida de los ",
      "Avenida de las ",
      "Avenida del ",
      "Avenida de ",
      "Avenida ",
      "Autovía del ",
      "Autovía de ",
      "Bulevar de ",
      "Bulevar ",
      "Travesía de las ",
      "Travesía de los ",
      "Travesía del ",
      "Travesía de ",
      "Travesía ",
      "Via de ",
      "Via ",
      "Viaducto de ",
      "Glorieta de ",
      "Glorieta del ",
      "Glorieta ",
      "Cuesta de ",
      "Costanilla de los",
      "Costanilla de ",
      "Carril bici ",
      "Avinguda d'",
      "Autovia de l'",
      "Avinguda de ",
      "Avinguda del ",
      "Avinguda dels ",
      "Avinguda ",
      "Baixada de la ",
      "Baixada del ",
      "Baixada de ",
      "Camí de la ",
      "Camí de l'",
      "Camí de ",
      "Carrer de les ",
      "Carrer de la ",
      "Carrer del ",
      "Carrer d'",
      "Carrer de ",
      "Carrer ",
      "Carreró de ",
      "Gran Via de les ",
      "Escales de la ",
      "Escales del ",
      "Escales d'",
      "Jardins de ",
      "Jardins del ",
      "Jardins dels ",
      "Moll de la ",
      "Moll de ",
      "Passatge d'",
      "Passatge de la ",
      "Passatge de les ",
      "Passatge del ",
      "Passatge dels ",
      "Passatge de ",
      "Passatge ",
      "Passeig de la ",
      "Passeig del ",
      "Passeig de ",
      "Passeig ",
      "Plaça d'",
      "Plaça de las ",
      "Plaça de la ",
      "Plaça de ",
      "Plaça del ",
      "Plaça dels ",
      "Plaça ",
      "Placeta de ",
      "Placeta ",
      "Pont del ",
      "Pont de ",
      "Rambla de ",
      "Rambla del ",
      "Rambla dels ",
      "Ronda de la ",
      "Ronda de ",
      "Rotonda de l'",
      "Rotonda de ",
      "Travessia de ",
      "Torrent de la ",
      "Torrent ",
      "Túnel de la ",
      "Túnel de  ",
      "Volta dels ",
      "Viaducte de "
    ) %>%
      stringr::str_c("^", .)
  ),
  tibble::tibble(
    country = "Germany",
    string = c(
      "strasse",
      "Strasse",
      "Straße",
      "straße",
      "weg",
      "Weg",
      "tunnel",
      "brücke",
      "promenade",
      "Platz",
      "platz",
      "allee",
      "steig",
      "Zeile",
      "hof"
    ) %>%
      stringr::str_c(., "$") %>%
      c(
        .,
        c(
          "Allee der ",
          "Allée du ",
          "Allée ",
          "Am "
        ) %>%
          stringr::str_c("^", .)
      )
  ),
  tibble::tibble(
    country = "France",
    string = c(
      "Rue de la ",
      "Rue de l'",
      "Rue de ",
      "Rue des ",
      "Rue du ",
      "Rue ",
      "Place de la ",
      "Place de ",
      "Place ",
      "Boulevard de la ",
      "Boulevard de ",
      "Boulevard ",
      "Allée du ",
      "Pont de la ",
      "Pont de ",
      "Pont d'",
      "Passerelle de ",
      "Passerelle ",
      "Chemin de la ",
      "Chemin de l'",
      "Chemin de ",
      "grande rue de "
    ) %>%
      stringr::str_c("^", .)
  ),
  tibble::tibble(
    country = "Portugal",
    string = c(
      "Alameda ",
      "Avenida das ",
      "Avenida da ",
      "Avenida dos ",
      "Avenida do ",
      "Avenida de ",
      "Avenida ",
      "Caminho do ",
      "Estrada da ",
      "Estrada das ",
      "Estrada dos ",
      "Estrada do ",
      "Estrada de ",
      "Estrada ",
      "Largo do ",
      "Largo da ",
      "Largo dos ",
      "Largo das ",
      "Largo de ",
      "Largo ",
      "Praça do ",
      "Praça da ",
      "Praça dos ",
      "Praça das ",
      "Praça de ",
      "Praça ",
      "Praceta da ",
      "Praceta de ",
      "Praceta ",
      "Rua da ",
      "Rua das ",
      "Rua dos ",
      "Rua do ",
      "Rua de ",
      "Rua ",
      "Travessa da ",
      "Travessa das ",
      "Travessa dos ",
      "Travessa do ",
      "Travessa de ",
      "Travessa "
    ) %>%
      stringr::str_c("^", .)
  ),
  tibble::tibble(
    country = "Hungary",
    string = c(
      " utca",
      " köz",
      " út",
      " tér",
      " utcája",
      " dűlő",
      " rakpart",
      " körút",
      " hid",
      " sétány",
      " felüljáró",
      " lejtő",
      " köz",
      " sugárút",
      " zug",
      " útfél",
      " liget"
    ) %>%
      stringr::str_c(., "$") %>%
      c(
        .,
        c("") %>%
          stringr::str_c("^", .)
      )
  ),
)

sn_street_name_to_remove_df %>% tail()
usethis::use_data(sn_street_name_to_remove_df,
  overwrite = TRUE
)
